/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health of the gateway and of every service (grpc.health.v1.Health/Check) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The gateway and the services it reaches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example gateway */
                            service?: string;
                            ok?: boolean;
                            services?: {
                                service?: string;
                                ok?: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the table types (listTableTypes) */
        get: operations["listTableTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/table-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Define or change a table type (defineTableType) */
        put: operations["defineTableType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the business parameters (getBusinessParameters) */
        get: operations["getBusinessParameters"];
        /** Change the business parameters; a field left out is unchanged (updateBusinessParameters) */
        put: operations["updateBusinessParameters"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone-maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the zone maps (listZoneMaps) */
        get: operations["listZoneMaps"];
        put?: never;
        /** Create a Draft zone map (createZoneMap) */
        post: operations["createZoneMap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone-maps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a zone map with its tables and the capacity per zone (getZoneMap) */
        get: operations["getZoneMap"];
        /** Change a zone map; a field left out is unchanged, an Active map accepts only the changes of UC-04 AF-1 (updateZoneMap) */
        put: operations["updateZoneMap"];
        post?: never;
        /** Discard a Draft zone map (discardDraftZoneMap) */
        delete: operations["discardDraftZoneMap"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone-maps/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store the image of the venue for the map (uploadZoneMapImage) */
        post: operations["uploadZoneMapImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone-maps/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a zone map, UC-04 S-1 (validateZoneMap) */
        post: operations["validateZoneMap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zone-maps/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a valid zone map; idempotent (activateZoneMap) */
        post: operations["activateZoneMap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The upcoming Published rounds with their status, not yet open, open or sold out (getUpcomingRounds) */
        get: operations["getUpcomingRounds"];
        put?: never;
        /** Create a Draft concert round (createRound) */
        post: operations["createRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a round with its tables and the hold period in force (getRound) */
        get: operations["getRound"];
        /** Change a round; a field left out is unchanged, a Published round accepts only the changes of UC-03 AF-3 (updateRound) */
        put: operations["updateRound"];
        post?: never;
        /** Discard a Draft round (discardDraftRound) */
        delete: operations["discardDraftRound"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tables of a round with zone, table type, capacity and package price (getRoundTables) */
        get: operations["getRoundTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a round, UC-03 S-1 (validateRound) */
        post: operations["validateRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a valid round; snapshots the business parameters and creates the table map of the round; idempotent (publishRound) */
        post: operations["publishRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}/table-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The status of every table of a round, polled every 2 seconds; 304 when the version is unchanged (getRoundTableStatus) */
        get: operations["getRoundTableStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hold a table; first lock wins (createHeldBooking) */
        post: operations["createHeldBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one of the caller's bookings (getBooking) */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/party-size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set the party size; the full table fee is computed in the same call (setPartySize) */
        put: operations["setPartySize"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The booking terms with the check-in window of the round (getBookingTerms) */
        get: operations["getBookingTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/terms-acceptance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the booking terms (acceptBookingTerms) */
        post: operations["acceptBookingTerms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the payment of the full table fee, UC-10 (startPayment); 501 in Increment 1 */
        post: operations["startPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a Held booking; the table is released at once (cancelBooking) */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}/e-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The e-ticket of a Confirmed booking (getETicket); 501 in progress 1 */
        get: operations["getETicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's customer profile; 404 before the first booking (getCustomerProfile) */
        get: operations["getCustomerProfile"];
        /** Correct the profile; a field left out is unchanged (updateCustomerProfile) */
        put: operations["updateCustomerProfile"];
        /** Create the profile with consent, UC-09 (createCustomerProfile) */
        post: operations["createCustomerProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/me/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Bookings, UC-06 (getCustomerBookings) */
        get: operations["getCustomerBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/check-ins/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a scanned booking reference, UC-02 S-1 (verifyBookingReference); 501 in progress 1 */
        post: operations["verifyBookingReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the entry; the booking becomes Checked-in (checkInBooking); 501 in progress 1 */
        post: operations["checkInBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The bookings of a round for the live view, UC-05 (getRoundBookings) */
        get: operations["getRoundBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The signed payment result of the Payment Gateway (receivePaymentResult); no session, the signature authenticates it (NFR-38) */
        post: operations["receivePaymentResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The status of a payment (getPaymentStatus) */
        get: operations["getPaymentStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in a staff account (signIn) */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out (signOut); the token comes from the Authorization header, "Bearer <token>" */
        delete: operations["signOut"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the staff accounts (listStaffAccounts) */
        get: operations["listStaffAccounts"];
        put?: never;
        /** Create a staff account (createStaffAccount) */
        post: operations["createStaffAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the role or the password of a staff account (updateStaffAccount) */
        put: operations["updateStaffAccount"];
        post?: never;
        /** Disable a staff account; it can no longer sign in (disableStaffAccount) */
        delete: operations["disableStaffAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            /** @description The service's detail of the error */
            details?: unknown;
        };
        TableTypeInput: {
            name: string;
            capacity: number;
            packageContent?: string;
        };
        TableType: {
            id: string;
        } & components["schemas"]["TableTypeInput"];
        BusinessParameters: {
            /** @description BRULE-02 */
            holdPeriodMinutes?: number;
            /** @description BRULE-04 */
            checkInWindowHours?: number;
            /** @description BRULE-05 */
            gracePeriodMinutes?: number;
            /** @description THB per person above the capacity of the table type */
            extraPersonFee?: number;
        };
        BusinessParametersUpdate: components["schemas"]["BusinessParameters"];
        Zone: {
            id?: string;
            name?: string;
        };
        ZoneMapTable: {
            /** @description unique in the map (FR-74) */
            tableNumber?: number;
            zoneId?: string;
            tableTypeId?: string;
            capacity?: number;
            x?: number;
            y?: number;
        };
        ZoneSummary: {
            zoneId?: string;
            name?: string;
            tables?: number;
            capacity?: number;
        };
        ZoneMap: {
            id?: string;
            name?: string;
            /** @enum {string} */
            status?: "Draft" | "Active";
            imageUrl?: string;
            zones?: components["schemas"]["Zone"][];
            tables?: components["schemas"]["ZoneMapTable"][];
            /** Format: date-time */
            createdAt?: string;
            /** @description tables and capacity per zone */
            summary?: components["schemas"]["ZoneSummary"][];
        };
        ZoneMapSummary: {
            id?: string;
            name?: string;
            /** @enum {string} */
            status?: "Draft" | "Active";
            tables?: number;
        };
        /** @description A field left out is unchanged */
        ZoneMapUpdate: {
            name?: string;
            zones?: components["schemas"]["Zone"][];
            tables?: components["schemas"]["ZoneMapTable"][];
        };
        ValidationResult: {
            valid?: boolean;
            problems?: string[];
        };
        PackagePrice: {
            zoneId?: string;
            tableTypeId?: string;
            /** @description THB (BRULE-08) */
            packagePrice?: number;
            packageContent?: string;
        };
        CheckInWindow: {
            roundId?: string;
            /**
             * Format: date-time
             * @description start minus the check-in window (BRULE-04)
             */
            opensAt?: string;
            /** Format: date-time */
            startAt?: string;
            /**
             * Format: date-time
             * @description start plus the grace period (BRULE-05)
             */
            graceEndsAt?: string;
        };
        /** @description A table of the round, the map joined with its table type and package price */
        RoundTable: {
            tableNumber?: number;
            zoneId?: string;
            zoneName?: string;
            tableTypeId?: string;
            tableTypeName?: string;
            capacity?: number;
            x?: number;
            y?: number;
            forSale?: boolean;
            /** @description absent until the round prices this zone and type */
            packagePrice?: number;
            packageContent?: string;
        };
        Round: {
            id?: string;
            name?: string;
            artist?: string;
            /** @enum {string} */
            status?: "Draft" | "Published";
            /**
             * Format: date
             * @description venue local date
             */
            date?: string;
            /** Format: date-time */
            doorsOpenAt?: string;
            /** Format: date-time */
            startAt?: string;
            /**
             * Format: date-time
             * @description BRULE-07
             */
            bookingOpenAt?: string;
            zoneMapId?: string;
            tablesNotForSale?: number[];
            prices?: components["schemas"]["PackagePrice"][];
            /** @description null until the round has a start time */
            checkInWindow?: components["schemas"]["CheckInWindow"] | null;
            /** @description snapshot at publish */
            parameters?: components["schemas"]["BusinessParameters"] | null;
            /** Format: date-time */
            createdAt?: string;
            /** @description in force for this round (BRULE-02) */
            holdPeriodMinutes?: number;
            tables?: components["schemas"]["RoundTable"][];
            /** @description after a change to a Published round */
            confirmedBookings?: number;
        };
        /** @description A field left out is unchanged */
        RoundUpdate: {
            name?: string;
            artist?: string;
            /** Format: date */
            date?: string;
            /** Format: date-time */
            doorsOpenAt?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            bookingOpenAt?: string;
            zoneMapId?: string;
            tablesNotForSale?: number[];
            prices?: components["schemas"]["PackagePrice"][];
        };
        UpcomingRound: {
            id?: string;
            name?: string;
            artist?: string;
            /** Format: date */
            date?: string;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            bookingOpenAt?: string;
            /** @enum {string} */
            status?: "not yet open" | "open" | "sold out";
            availableTables?: number;
            tablesForSale?: number;
        };
        TableStatus: {
            tableNumber?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "HELD" | "BOOKED" | "OCCUPIED" | "NOT_FOR_SALE";
            /** @description empty when free */
            bookingId?: string;
            /** @description RFC 3339 */
            holdEndsAt?: string;
        };
        /** @description The read model of the table map (ADR-13) */
        RoundTableStatus: {
            roundId?: string;
            /** @description grows on every change; the ETag of the polled read (ADR-09) */
            version?: number;
            tables?: components["schemas"]["TableStatus"][];
        };
        Fee: {
            /** @description BRULE-08 */
            packagePrice?: number;
            extraPersons?: number;
            /** @description BRULE-09 */
            extraPersonFee?: number;
            /** @description BRULE-01 */
            fullTableFee?: number;
        };
        /** @description One transition of the booking, its audit trail (ADR-13) */
        StatusChange: {
            status?: string;
            /** Format: date-time */
            at?: string;
            by?: string;
        };
        Booking: {
            id?: string;
            /** @description LINE user id (BRULE-12) */
            customerId?: string;
            roundId?: string;
            tableNumber?: number;
            /** @description copied from the round at hold time (BRULE-07) */
            zoneId?: string;
            zoneName?: string;
            tableTypeId?: string;
            capacity?: number;
            /** @enum {string} */
            status?: "Held" | "Confirmed" | "Checked-in" | "Cancelled" | "Expired" | "No-show";
            /**
             * Format: date-time
             * @description BRULE-02
             */
            holdEndsAt?: string;
            /** @description absent until set */
            partySize?: number;
            fee?: components["schemas"]["Fee"] | null;
            /** @description BRULE-16 */
            termsAccepted?: boolean;
            /** Format: date-time */
            createdAt?: string;
            history?: components["schemas"]["StatusChange"][];
            /** @description 0 unless Held */
            remainingHoldSeconds?: number;
        };
        CustomerProfileCreate: {
            name: string;
            /** @description Thai mobile number */
            phone: string;
            /** @description PDPA consent to the data collection (FR-10 */
            consent: boolean;
        };
        CustomerProfileUpdate: {
            name?: string;
            phone?: string;
        };
        CustomerProfile: {
            customerId?: string;
            name?: string;
            phone?: string;
            /** Format: date-time */
            consentAt?: string;
        };
        BookingTerms: {
            bookingId?: string;
            terms?: string[];
            checkInWindow?: components["schemas"]["CheckInWindow"];
        };
        PaymentRequest: {
            paymentId?: string;
            /**
             * Format: uri
             * @description the hosted checkout of the Payment Gateway
             */
            checkoutUrl?: string;
        };
        ETicket: {
            bookingId?: string;
            bookingReference?: string;
            /** @description the signed booking reference */
            qrPayload?: string;
        };
        BookingReference: {
            bookingReference: string;
        };
        VerificationResult: {
            valid?: boolean;
            booking?: components["schemas"]["Booking"] | null;
            /** @description why the ticket is not valid (UC-02 EF-1 */
            reason?: string;
        };
        /** @description The signed result that the Payment Gateway posts (NFR-38) */
        PaymentResult: {
            paymentId: string;
            /** @enum {string} */
            status: "Paid" | "Failed";
            amount: number;
            signature: string;
        };
        PaymentStatus: {
            paymentId?: string;
            bookingId?: string;
            /** @enum {string} */
            status?: "Pending" | "Paid" | "Failed";
            amount?: number;
        };
        Session: {
            token?: string;
            /** @enum {string} */
            role?: "manager" | "front_staff" | "owner";
            staffAccountId?: string;
        };
        StaffAccountCreate: {
            username: string;
            /** @enum {string} */
            role: "manager" | "front_staff" | "owner";
            /** Format: password */
            password: string;
        };
        /** @description A field left out is unchanged */
        StaffAccountUpdate: {
            /** @enum {string} */
            role?: "manager" | "front_staff" | "owner";
            /** Format: password */
            password?: string;
        };
        StaffAccount: {
            staffAccountId?: string;
            username?: string;
            /** @enum {string} */
            role?: "manager" | "front_staff" | "owner";
            /** @enum {string} */
            status?: "Active" | "Disabled";
        };
    };
    responses: {
        /** @description Invalid input; details may list the problems */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No identity */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The role may not call this route (FR-66) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A rule refuses the change */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not built in this increment */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The service or one of its collaborators is down */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Removed */
        Removed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    removed?: boolean;
                };
            };
        };
        /** @description The validation result */
        ValidationResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationResult"];
            };
        };
    };
    parameters: {
        id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTableTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The table types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableType"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    defineTableType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableTypeInput"];
            };
        };
        responses: {
            /** @description The table type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableType"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getBusinessParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The parameters in force */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessParameters"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateBusinessParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessParametersUpdate"];
            };
        };
        responses: {
            /** @description The parameters now in force */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessParameters"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listZoneMaps: {
        parameters: {
            query?: {
                /** @description Only the maps in this status */
                status?: "Draft" | "Active";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The maps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMapSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createZoneMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description The new map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getZoneMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateZoneMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneMapUpdate"];
            };
        };
        responses: {
            /** @description The map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    discardDraftZoneMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Removed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    uploadZoneMapImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fileName: string;
                };
            };
        };
        responses: {
            /** @description The map with its imageUrl */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMap"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    validateZoneMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ValidationResult"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    activateZoneMap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Active map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMap"];
                };
            };
            /** @description The map is not valid; details lists the problems */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getUpcomingRounds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rounds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingRound"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description The new round */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The round */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundUpdate"];
            };
        };
        responses: {
            /** @description The round */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    discardDraftRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Removed"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getRoundTables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundTable"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    validateRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ValidationResult"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    publishRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Published round */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            /** @description The round is not valid; details lists the problems */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["Unavailable"];
        };
    };
    getRoundTableStatus: {
        parameters: {
            query?: never;
            header?: {
                /** @description The version the caller already has */
                "If-None-Match"?: string;
            };
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The table map of the round */
            200: {
                headers: {
                    /** @description The version of the map */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundTableStatus"];
                };
            };
            /** @description Unchanged since the version in If-None-Match */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createHeldBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    roundId: string;
                    tableNumber: number;
                };
            };
        };
        responses: {
            /** @description The Held booking with its remaining hold seconds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The round is not open or the table was just taken by another customer (UC-01 AF-3) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setPartySize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    partySize: number;
                };
            };
        };
        responses: {
            /** @description The booking with its fee */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getBookingTerms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The terms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingTerms"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptBookingTerms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking with termsAccepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    startPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payment request with the checkout URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            501: components["responses"]["NotImplemented"];
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Cancelled booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getETicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The e-ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ETicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    getCustomerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCustomerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerProfileUpdate"];
            };
        };
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCustomerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerProfileCreate"];
            };
        };
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getCustomerBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    verifyBookingReference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingReference"];
            };
        };
        responses: {
            /** @description The verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            501: components["responses"]["NotImplemented"];
        };
    };
    checkInBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingReference"];
            };
        };
        responses: {
            /** @description The Checked-in booking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            501: components["responses"]["NotImplemented"];
        };
    };
    getRoundBookings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bookings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    receivePaymentResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentResult"];
            };
        };
        responses: {
            /** @description Accepted; a duplicate result is ignored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                    };
                };
            };
            /** @description The signature does not verify */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getPaymentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description The session token and the role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Wrong username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: {
                /** @description Bearer <session token> */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listStaffAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createStaffAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffAccountCreate"];
            };
        };
        responses: {
            /** @description The account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateStaffAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffAccountUpdate"];
            };
        };
        responses: {
            /** @description The account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    disableStaffAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Disabled account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
