// The API types, re-exported from the OpenAPI components (src/api-types.d.ts, generated by `npm run api-types`).
import type { components, paths } from './api-types';

export type { paths };
export type Schemas = components['schemas'];

export type ErrorBody = Schemas['Error'];
export type TableType = Schemas['TableType'];
export type TableTypeInput = Schemas['TableTypeInput'];
export type BusinessParameters = Schemas['BusinessParameters'];
export type Zone = Schemas['Zone'];
export type ZoneMapTable = Schemas['ZoneMapTable'];
export type ZoneSummary = Schemas['ZoneSummary'];
export type ZoneMap = Schemas['ZoneMap'];
export type ZoneMapSummary = Schemas['ZoneMapSummary'];
export type ZoneMapUpdate = Schemas['ZoneMapUpdate'];
export type ValidationResult = Schemas['ValidationResult'];
export type PackagePrice = Schemas['PackagePrice'];
export type CheckInWindow = Schemas['CheckInWindow'];
export type RoundTable = Schemas['RoundTable'];
export type Round = Schemas['Round'];
export type RoundUpdate = Schemas['RoundUpdate'];
export type UpcomingRound = Schemas['UpcomingRound'];
export type TableStatus = Schemas['TableStatus'];
export type TableStatusValue = NonNullable<TableStatus['status']>;
export type RoundTableStatus = Schemas['RoundTableStatus'];
export type Fee = Schemas['Fee'];
export type Booking = Schemas['Booking'];
export type BookingStatus = NonNullable<Booking['status']>;
export type CustomerProfile = Schemas['CustomerProfile'];
export type CustomerProfileCreate = Schemas['CustomerProfileCreate'];
export type CustomerProfileUpdate = Schemas['CustomerProfileUpdate'];
export type BookingTerms = Schemas['BookingTerms'];
export type PaymentRequest = Schemas['PaymentRequest'];
export type PaymentStatus = Schemas['PaymentStatus'];
export type ETicket = Schemas['ETicket'];
export type BookingReference = Schemas['BookingReference'];
export type VerificationResult = Schemas['VerificationResult'];
export type StaffSession = Schemas['Session'];
export type StaffRole = NonNullable<StaffSession['role']>;
export type StaffAccount = Schemas['StaffAccount'];
export type StaffAccountCreate = Schemas['StaffAccountCreate'];
export type StaffAccountUpdate = Schemas['StaffAccountUpdate'];
export interface Removed { removed?: boolean }
